var available_modules =
[
    [ "BEModule", "d1/dc0/BEModule.html", null ],
    [ "BVModule", "d9/d3c/BVModule.html", null ],
    [ "CNFerModule", "d7/dc7/CNFerModule.html", null ],
    [ "CSplitModule", "d5/d70/CSplitModule.html", null ],
    [ "CoCoAGBModule", "d1/d17/CoCoAGBModule.html", null ],
    [ "CubeLIAModule", "d8/df0/CubeLIAModule.html", null ],
    [ "CurryModule", "db/d8c/CurryModule.html", null ],
    [ "EMModule", "d9/d14/EMModule.html", null ],
    [ "ESModule", "de/ddf/ESModule.html", null ],
    [ "FPPModule", "da/d34/FPPModule.html", null ],
    [ "GBModule", "d8/d60/GBModule.html", null ],
    [ "GBPPModule", "df/d5c/GBPPModule.html", null ],
    [ "ICEModule", "df/d86/ICEModule.html", null ],
    [ "ICPModule", "db/d61/ICPModule.html", null ],
    [ "IncWidthModule", "d1/dc9/IncWidthModule.html", null ],
    [ "IntBlastModule", "d0/d29/IntBlastModule.html", null ],
    [ "IntEqModule", "d4/dfc/IntEqModule.html", null ],
    [ "LRAModule", "d0/d34/LRAModule.html", null ],
    [ "LVEModule", "d7/d2e/LVEModule.html", null ],
    [ "MCBModule", "dc/d42/MCBModule.html", null ],
    [ "NRAILModule", "dd/d53/NRAILModule.html", null ],
    [ "NewCADModule", "db/d4e/NewCADModule.html", null ],
    [ "PBGaussModule", "d3/d6e/PBGaussModule.html", null ],
    [ "PBPPModule", "df/d9a/PBPPModule.html", null ],
    [ "PFEModule", "d0/d29/PFEModule.html", null ],
    [ "PNFerModule", "d2/d80/PNFerModule.html", null ],
    [ "SATModule", "da/db4/SATModule.html", null ],
    [ "STropModule", "d7/dd5/STropModule.html", null ],
    [ "SplitSOSModule", "d8/de1/SplitSOSModule.html", null ],
    [ "SymmetryModule", "d2/dd1/SymmetryModule.html", null ],
    [ "VSModule", "d6/db7/VSModule.html", null ]
];